alias install="sudo aptitude install -y"
alias remove="sudo aptitude purge"
alias search="aptitude search"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias c="clear"
alias ginit="git init"
alias gst="git status"
alias gra="git remote add"
alias gad="git add"
alias gcm="git commit -m"
alias gpu="git push"
alias gcl="git clone"


